name: atis-constraint
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - numpy
  - scipy
  - matplotlib
  - seaborn
  - pyyaml
  - jupyter
  - jupyterlab
  - pip
  - pip:
    - statsmodels
